services:
  ferramentas-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ferramentas-7bpm
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    # Garantir que o arquivo .env seja carregado corretamente
    env_file:
      - .env